#name: DianMingServer
#version: 0.0.1
#description: A simple console application.
#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'
name: DianMingServer
description: A sample web application
dependencies:
  json_object: any
  browser: any
